/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hw08;

import java.awt.Color;
import javax.swing.event.ChangeEvent;

/**
 *
 * @author yunti
 */
public class P195 extends javax.swing.JFrame {

    /**
     * Creates new form P195
     */
    public P195() {
        initComponents();
        int r = jSlider_red.getValue();
        int g = jSlider_green.getValue();
        int b = jSlider_blue.getValue();
        
        jPanel_color.setBackground(new Color(r,g,b));
    }
//    public interface ChangeListener{
//        void staticChanged(ChangeEvent ce);
////        int value = jSlider_red.getValue();
//    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSlider_red = new javax.swing.JSlider();
        jSlider_green = new javax.swing.JSlider();
        jSlider_blue = new javax.swing.JSlider();
        red = new javax.swing.JLabel();
        green = new javax.swing.JLabel();
        blue = new javax.swing.JLabel();
        jPanel_color = new javax.swing.JPanel();
        jTextField_red = new javax.swing.JTextField();
        jTextField_green = new javax.swing.JTextField();
        jTextField_blue = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jSlider_red.setMajorTickSpacing(20);
        jSlider_red.setMaximum(255);
        jSlider_red.setMinorTickSpacing(5);
        jSlider_red.setPaintTicks(true);
        jSlider_red.setSnapToTicks(true);
        jSlider_red.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSlider_redStateChanged(evt);
            }
        });

        jSlider_green.setMajorTickSpacing(20);
        jSlider_green.setMaximum(255);
        jSlider_green.setMinorTickSpacing(5);
        jSlider_green.setPaintTicks(true);
        jSlider_green.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSlider_greenStateChanged(evt);
            }
        });

        jSlider_blue.setMajorTickSpacing(20);
        jSlider_blue.setMaximum(255);
        jSlider_blue.setMinorTickSpacing(5);
        jSlider_blue.setPaintTicks(true);
        jSlider_blue.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSlider_blueStateChanged(evt);
            }
        });

        red.setText("Red");

        green.setText("Green");

        blue.setText("Blue");

        javax.swing.GroupLayout jPanel_colorLayout = new javax.swing.GroupLayout(jPanel_color);
        jPanel_color.setLayout(jPanel_colorLayout);
        jPanel_colorLayout.setHorizontalGroup(
            jPanel_colorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 120, Short.MAX_VALUE)
        );
        jPanel_colorLayout.setVerticalGroup(
            jPanel_colorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 159, Short.MAX_VALUE)
        );

        jTextField_red.setActionCommand("<Not Set>");
        jTextField_red.setEnabled(false);
        jTextField_red.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_redActionPerformed(evt);
            }
        });

        jTextField_green.setEnabled(false);
        jTextField_green.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_greenActionPerformed(evt);
            }
        });

        jTextField_blue.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(red)
                    .addComponent(green)
                    .addComponent(blue))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSlider_blue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSlider_green, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSlider_red, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField_red, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                    .addComponent(jTextField_green)
                    .addComponent(jTextField_blue))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(jPanel_color, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jSlider_red, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(red)
                            .addComponent(jTextField_red, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jSlider_green, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(green)
                            .addComponent(jTextField_green, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jSlider_blue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(blue)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jTextField_blue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(26, Short.MAX_VALUE)
                        .addComponent(jPanel_color, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(39, 39, 39))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_greenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_greenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_greenActionPerformed

    private void jTextField_redActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_redActionPerformed
        // TODO add your handling code here:
        jTextField_red.setText(String.valueOf(jSlider_red.getValue()));
    }//GEN-LAST:event_jTextField_redActionPerformed

    private void jSlider_redStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSlider_redStateChanged
        // TODO add your handling code here:
        this.jTextField_red.setText(""+this.jSlider_red.getValue());
        jPanel_color.setBackground(new Color(this.jSlider_red.getValue(),this.jSlider_green.getValue(),this.jSlider_blue.getValue()));
    }//GEN-LAST:event_jSlider_redStateChanged

    private void jSlider_greenStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSlider_greenStateChanged
        // TODO add your handling code here:
        this.jTextField_green.setText(""+this.jSlider_green.getValue());
        jPanel_color.setBackground(new Color(this.jSlider_red.getValue(),this.jSlider_green.getValue(),this.jSlider_blue.getValue()));
    }//GEN-LAST:event_jSlider_greenStateChanged

    private void jSlider_blueStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSlider_blueStateChanged
        // TODO add your handling code here:
        this.jTextField_blue.setText(""+this.jSlider_blue.getValue());
        jPanel_color.setBackground(new Color(this.jSlider_red.getValue(),this.jSlider_green.getValue(),this.jSlider_blue.getValue()));
    }//GEN-LAST:event_jSlider_blueStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(P195.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(P195.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(P195.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(P195.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
       
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new P195().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel blue;
    private javax.swing.JLabel green;
    private javax.swing.JPanel jPanel_color;
    private javax.swing.JSlider jSlider_blue;
    private javax.swing.JSlider jSlider_green;
    private javax.swing.JSlider jSlider_red;
    private javax.swing.JTextField jTextField_blue;
    private javax.swing.JTextField jTextField_green;
    private javax.swing.JTextField jTextField_red;
    private javax.swing.JLabel red;
    // End of variables declaration//GEN-END:variables
}
