/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hw08;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileFilter;
/**
 *
 * @author yunti
 */
public class P206 extends javax.swing.JFrame {

    /**
     * Creates new form P206
     */
    
    String srcFile="";
    File fin = new File(srcFile);
    String baseDir = "d:/";
    JFileChooser chooser = new JFileChooser(baseDir);
    String File_ = "";
    public P206() {
        initComponents();
        this.setSize(400, 300);
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea = new javax.swing.JTextArea();
        jButton_open = new javax.swing.JButton();
        jButton_save = new javax.swing.JButton();
        jButton_saveAs = new javax.swing.JButton();
        jTextField_file = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout());

        jTextArea.setColumns(20);
        jTextArea.setRows(5);
        jScrollPane2.setViewportView(jTextArea);

        jButton_open.setText("Open");
        jButton_open.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_openActionPerformed(evt);
            }
        });

        jButton_save.setText("Save");
        jButton_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_saveActionPerformed(evt);
            }
        });

        jButton_saveAs.setText("Save As...");
        jButton_saveAs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_saveAsActionPerformed(evt);
            }
        });

        jTextField_file.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_fileActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jButton_open)
                        .addGap(18, 18, 18)
                        .addComponent(jButton_save)
                        .addGap(18, 18, 18)
                        .addComponent(jButton_saveAs)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField_file, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_open)
                    .addComponent(jButton_save)
                    .addComponent(jButton_saveAs)
                    .addComponent(jTextField_file, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_fileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_fileActionPerformed
        // TODO add your handling code here:
        File_ = jTextField_file.getText();
    }//GEN-LAST:event_jTextField_fileActionPerformed

    private void jButton_openActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_openActionPerformed
        // TODO add your handling code here:
        File destFile = new File(baseDir);
       int code = chooser.showDialog(null, "Choose Src File");
       switch (code) {
            case JFileChooser.APPROVE_OPTION:
                destFile = chooser.getSelectedFile();
                jTextField_file.setText(destFile.toString());
                srcFile = destFile.toString();
        //            	System.out.println(srcFile);
                FileReader fr = null;
                try {
                    fr = new FileReader(destFile);
                } catch (FileNotFoundException ex) {
                    Logger.getLogger(P206.class.getName()).log(Level.SEVERE, null, ex);
                }
        //                FileWriter fw = new FileWriter(destFile);
                BufferedReader br = new BufferedReader(fr);
        //		BufferedWriter bw = new BufferedWriter(fw);
                String aLine;
                String text = "";
                try {
                    while((aLine=br.readLine())!=null) {
                        text += aLine+"\n";
                    }
                } catch (IOException ex) {
                    Logger.getLogger(P206.class.getName()).log(Level.SEVERE, null, ex);
                }
                jTextArea.setText(text);
                try {      
                    fr.close();
        //                fw.close();
                } catch (IOException ex) {
                    Logger.getLogger(P206.class.getName()).log(Level.SEVERE, null, ex);
                }
            case JFileChooser.CANCEL_OPTION:
//        		System.out.println("Bye!");
        		break;
        	default:
        		// ERROR !
       }        
    }//GEN-LAST:event_jButton_openActionPerformed
    
    private void jButton_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_saveActionPerformed
        // TODO add your handling code here:
        File destFile = new File(srcFile);
        FileWriter fw = null;
        try {
            fw = new FileWriter(destFile);
        } catch (IOException ex) {
            Logger.getLogger(P206.class.getName()).log(Level.SEVERE, null, ex);
        }
        BufferedWriter bw = new BufferedWriter(fw);
        String[] aLine = jTextArea.getText().split("\n");
        
        for(int i=0 ; i<aLine.length ; i++) {
            try {
                bw.write(aLine[i]+"\n");
            } catch (IOException ex) {
                Logger.getLogger(P206.class.getName()).log(Level.SEVERE, null, ex);
            }
	}System.out.println("save "+ srcFile+" fin");
        try {
            bw.close();
        } catch (IOException ex) {
            Logger.getLogger(P206.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton_saveActionPerformed

    private void jButton_saveAsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_saveAsActionPerformed
        // TODO add your handling code here:
        File destFile = new File(jTextField_file.getText());
        FileWriter fw = null;
        try {
            fw = new FileWriter(destFile);
        } catch (IOException ex) {
            Logger.getLogger(P206.class.getName()).log(Level.SEVERE, null, ex);
        }
        BufferedWriter bw = new BufferedWriter(fw);
        String[] aLine = jTextArea.getText().split("\n");
        
        for(int i=0 ; i<aLine.length ; i++) {
            try {
                bw.write(aLine[i]+"\n");
            } catch (IOException ex) {
                Logger.getLogger(P206.class.getName()).log(Level.SEVERE, null, ex);
            }
	}System.out.println("save as "+ jTextField_file.getText()+" fin");
        try {
            bw.close();
        } catch (IOException ex) {
            Logger.getLogger(P206.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton_saveAsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(P206.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(P206.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(P206.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(P206.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new P206().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_open;
    private javax.swing.JButton jButton_save;
    private javax.swing.JButton jButton_saveAs;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea;
    private javax.swing.JTextField jTextField_file;
    // End of variables declaration//GEN-END:variables
}
